### PR TITLE
Added Jsdoc support

### PR DESCRIPTION
**Pull request by guiguan**
- Added jsdoc support. User can document their API using Jsdoc right in their service class definition
- Fixed an issue that id param is not showing correctly
- Bumped node requirement to > 6.0.0

### CODE REVIEW

**Comment by daffl** [comment]
This looks like a good addition, thank you. A couple of notes:

- Are there any tests that can be written for this feature?
- Infrastructure changes shouldn't be necessary (or suggested in PR separate from the feature)
  - The `lib` folder should still be ignored. Transpiled files shouldn't be added to the repository
  - In general we support all Node versions [according to the LTS schedule](https://github.com/nodejs/LTS) so 4.0 is still relevant
  - The version number in `package.json` will be bumped automatically upon publishing

**Comment by guiguan** [comment]
Cool, I ll make those changes in the coming weekend

**Comment by guiguan** [comment]
Sorry, this work is delayed because I am thinking of using esdoc parser and support esdoc syntax, which is almost backward compatible with jsdoc and more succinct

**Comment by JigSawFr** [comment]
Seems to be great !

**Comment by daffl** [comment]
@guiguan Still any interest in getting this in?

**Comment by guiguan** [comment]
Yes!

**Comment by daffl** [comment]
Cool. If you can address my comments and merge with latest we can get it in.

**Comment by daffl** [comment]
@guiguan Really appreciate the PR and I think it would be a great change but this branch has diverged quite a bit now so I am going to close this PR. Looking forward to a resubmission with the changes we discussed 😄

**Pull request closed without merging**
