### PR TITLE
upgrate swagger to 2.0

### PR DESCRIPTION
**Pull request by lpreterite**

### CODE REVIEW

**Comment by daffl** [comment]
I like where this is going 😃  One question:

Is there a Swagger NPM module so that we don't have to check in the `bower_components`?

**Comment by daffl** [comment]
E.g. adding https://www.npmjs.com/package/swagger-ui to the dependencies and linking to it?

**Comment by lpreterite** [comment]
I was going to use NPM module instead of bower :-)

**Comment by daffl** [comment]
Sweet. If you can update the pull request to use it we can start getting an updated release ready 😄

**Comment by daffl** [comment]
Thank you again, this is great! I will try and update the plugin to our new infrastructure over the weekend, add some tests and make a v0.3.0 release.

**Comment by daffl** [comment]
@lpreterite Thanks again! I released the updated version as 0.3.0. One thing I changed was moving things like `new feathersSwagger.utils.Definition` to `feathersSwagger.definition`, everything else should still work the same.

**Comment by lpreterite** [comment]
Another problem in this version, property type not converted successfully, please update the following code

```
# utils.js@definition
keys.forEach(function (attrName) {
    let attr = model.attributes[attrName];
    let attrType = typeof attr.key !== 'undefined' ? attr.key : attr.type.constructor.prototype.key;
    var prop = property(attrType, model.attributes[attrName].type);

    result.properties[attrName] = prop;
});
```

**Pull request merged**
